services:
  - type: web
    name: site-searcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app --bind 0.0.0.0:10000 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: CONCURRENT_REQUESTS
        value: "30"
